<#
.SYNOPSIS
Builds a single-file, paste-ready NinjaOne Reparo deployment script.

.DESCRIPTION
Ninja regular scripts do not accept helper files and Ninja installers accept only
binary installer formats. This generator embeds a gzip-compressed Reparo.ps1 payload
in one PowerShell script so it can be pasted directly into a Ninja automation.
#>
[CmdletBinding()]
param(
    [string]$ReparoPath,
    [string]$OutputPath,
    [string]$DeploymentLabel = 'NinjaOne',
    [string]$NinjaCustomFieldName = 'Reparo'
)

$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($ReparoPath)) {
    $ReparoPath = Join-Path $PSScriptRoot '..\Reparo.ps1'
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $PSScriptRoot 'Ninja-Embedded.ps1'
}

$sourcePath = (Resolve-Path -LiteralPath $ReparoPath).Path
$sourceBytes = [System.IO.File]::ReadAllBytes($sourcePath)
$sourceHash = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash

$compressedStream = [System.IO.MemoryStream]::new()
$gzip = [System.IO.Compression.GZipStream]::new(
    $compressedStream,
    [System.IO.Compression.CompressionLevel]::Optimal,
    $true
)
try {
    $gzip.Write($sourceBytes, 0, $sourceBytes.Length)
}
finally {
    $gzip.Dispose()
}

$base64 = [Convert]::ToBase64String($compressedStream.ToArray())
$base64Lines = [regex]::Matches($base64, '.{1,120}') | ForEach-Object { "    '$($_.Value)'" }
$base64Literal = "@(`n$($base64Lines -join "`n")`n) -join ''"

$template = @'
<#
.SYNOPSIS
Self-contained Reparo deployment for __DEPLOYMENT_LABEL__.

.DESCRIPTION
Generated by deploy/New-NinjaEmbeddedDeployment.ps1. It contains a reviewed Reparo
payload, installs that payload first, optionally refreshes it from GitHub, then runs
the requested Reparo mode. No helper-file attachment is required.
#>
[CmdletBinding()]
param(
    [string]$InstallRoot = "$env:ProgramData\Reparo",
    [string]$LogRoot = "$env:ProgramData\Reparo\Logs",
    [string]$InstallOnly = 'false',
    [string]$ReportOnly = 'false',
    [string]$Offline = 'false',
    [string]$RefreshFromGitHub = 'true',
    [string]$RemoteReparoUrl = 'https://raw.githubusercontent.com/16thdoc/Reparo/main/Reparo.ps1',
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ReparoArguments
)

$ErrorActionPreference = 'Stop'
$bundledSha256 = '__BUNDLED_SHA256__'
$bundledGzipBase64 = __BUNDLED_GZIP_BASE64__

function Convert-DeploymentToggle {
    param(
        [string]$Value,
        [bool]$Default,
        [string]$Name
    )

    # NinjaOne can pass the literal type name "System.String" for an omitted
    # imported-script field. Treat it as omitted instead of failing parameter binding.
    $normalized = if ($null -eq $Value) { '' } else { $Value.Trim().ToLowerInvariant() }
    if ([string]::IsNullOrWhiteSpace($normalized) -or $normalized -eq 'system.string') {
        return $Default
    }

    if ($normalized -in @('true', '$true', '1', 'yes', 'on')) { return $true }
    if ($normalized -in @('false', '$false', '0', 'no', 'off')) { return $false }
    throw "$Name must be true or false; received '$Value'."
}

function Resolve-DeploymentString {
    param(
        [string]$Value,
        [string]$Default
    )

    if ([string]::IsNullOrWhiteSpace($Value) -or $Value.Trim() -eq 'System.String') {
        return $Default
    }

    return $Value
}

$InstallRoot = Resolve-DeploymentString -Value $InstallRoot -Default "$env:ProgramData\Reparo"
$LogRoot = Resolve-DeploymentString -Value $LogRoot -Default "$env:ProgramData\Reparo\Logs"
$RemoteReparoUrl = Resolve-DeploymentString -Value $RemoteReparoUrl -Default 'https://raw.githubusercontent.com/16thdoc/Reparo/main/Reparo.ps1'
$installOnlyRequested = Convert-DeploymentToggle -Value $InstallOnly -Default $false -Name 'InstallOnly'
$reportOnlyRequested = Convert-DeploymentToggle -Value $ReportOnly -Default $false -Name 'ReportOnly'
$offlineRequested = Convert-DeploymentToggle -Value $Offline -Default $false -Name 'Offline'
$refreshRequested = Convert-DeploymentToggle -Value $RefreshFromGitHub -Default $true -Name 'RefreshFromGitHub'
if ($offlineRequested) {
    $refreshRequested = $false
}

__NINJA_CUSTOM_FIELD_BLOCK__

function Invoke-ReparoInstaller {
    param(
        [Parameter(Mandatory)]
        [string]$BootstrapPath,
        [Parameter(Mandatory)]
        [string]$SourceUrl
    )

    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $BootstrapPath -New -InstallRoot $InstallRoot -LogRoot $LogRoot -SourceUrl $SourceUrl
    if ($LASTEXITCODE -ne 0) {
        throw "Reparo installer failed with exit code $LASTEXITCODE."
    }
}

$payloadDirectory = Join-Path $env:TEMP 'Reparo-Ninja'
$payloadPath = Join-Path $payloadDirectory "Reparo-$bundledSha256.ps1"
New-Item -ItemType Directory -Path $payloadDirectory -Force | Out-Null

try {
    $compressedBytes = [Convert]::FromBase64String($bundledGzipBase64)
    $input = [System.IO.MemoryStream]::new($compressedBytes)
    $gzip = [System.IO.Compression.GZipStream]::new($input, [System.IO.Compression.CompressionMode]::Decompress)
    $output = [System.IO.MemoryStream]::new()
    try {
        $gzip.CopyTo($output)
        [System.IO.File]::WriteAllBytes($payloadPath, $output.ToArray())
    }
    finally {
        $output.Dispose()
        $gzip.Dispose()
        $input.Dispose()
    }

    $actualHash = (Get-FileHash -LiteralPath $payloadPath -Algorithm SHA256).Hash
    if ($actualHash -ne $bundledSha256) {
        throw "Embedded Reparo SHA-256 mismatch. Expected $bundledSha256; got $actualHash."
    }

    Write-Host '=== __DEPLOYMENT_LABEL__ Reparo Embedded Deployer ==='
    Write-Host "Computer: $env:COMPUTERNAME"
    Write-Host "Bundled SHA-256: $bundledSha256"
    Write-Host "Install root: $InstallRoot"
    Write-Host "Offline mode: $offlineRequested"
    Write-Host "Remote refresh: $refreshRequested"
    if ($refreshRequested) {
        Write-Host "Remote source: $RemoteReparoUrl"
    }

    Write-Host 'Installing the embedded Reparo payload.'
    Invoke-ReparoInstaller -BootstrapPath $payloadPath -SourceUrl $payloadPath

    $installedPath = Join-Path $InstallRoot 'Reparo.ps1'
    if (-not (Test-Path -LiteralPath $installedPath -PathType Leaf)) {
        throw "Bundled installation reported success but runtime was not found: $installedPath"
    }

    if ($refreshRequested) {
        try {
            Write-Host 'Checking GitHub for a newer Reparo runtime.'
            Invoke-ReparoInstaller -BootstrapPath $installedPath -SourceUrl $RemoteReparoUrl
            Write-Host 'GitHub refresh completed.'
        }
        catch {
            Write-Warning "GitHub refresh failed; continuing with the embedded runtime. $($_.Exception.Message)"
        }
    }

__NINJA_CUSTOM_FIELD_UPDATE__

    if ($installOnlyRequested -or -not ($ReparoArguments -and $ReparoArguments.Count -gt 0)) {
        Write-Host 'Install-only mode complete; maintenance was not run.'
        exit 0
    }

    $arguments = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $installedPath, '-LogRoot', $LogRoot)
    if ($ReparoArguments -and $ReparoArguments.Count -gt 0) {
        $arguments += $ReparoArguments
    }
    Write-Host ("Launching installed Reparo: powershell.exe {0}" -f ($arguments -join ' '))
    & powershell.exe @arguments
    $exitCode = $LASTEXITCODE
    Write-Host "Reparo exit code: $exitCode"
    exit $exitCode
}
finally {
    Remove-Item -LiteralPath $payloadPath -Force -ErrorAction SilentlyContinue
}
'@

$ninjaCustomFieldBlock = ''
$ninjaCustomFieldUpdate = ''
if (-not [string]::IsNullOrWhiteSpace($NinjaCustomFieldName)) {
    $escapedCustomFieldName = $NinjaCustomFieldName.Replace("'", "''")
    $ninjaCustomFieldBlock = @"
function Update-NinjaReparoCustomField {
    param(
        [Parameter(Mandatory)]
        [string]`$ReparoPath,
        [switch]`$Required
    )

    `$version = 'Not installed'
    if (Test-Path -LiteralPath `$ReparoPath -PathType Leaf) {
        `$match = Select-String -LiteralPath `$ReparoPath -Pattern "ReparoVersion\s*=\s*'([^']+)'" | Select-Object -First 1
        if (`$match -and `$match.Matches[0].Groups[1].Value) {
            `$version = `$match.Matches[0].Groups[1].Value
        }
        else {
            `$version = 'Installed (version unreadable)'
        }
    }

    `$propertySetter = Get-Command -Name Ninja-Property-Set -ErrorAction SilentlyContinue
    if (-not `$propertySetter) {
        `$message = 'Ninja-Property-Set is unavailable; the Reparo custom field was not updated.'
        if (`$Required) { throw `$message }
        Write-Warning `$message
        return
    }

    & `$propertySetter.Name '$escapedCustomFieldName' `$version
    if (`$null -ne `$LASTEXITCODE -and `$LASTEXITCODE -ne 0) {
        throw "Ninja-Property-Set failed with exit code `$LASTEXITCODE."
    }
    Write-Host "Ninja custom field '$escapedCustomFieldName' set to: `$version"
}

if (`$reportOnlyRequested) {
    Update-NinjaReparoCustomField -ReparoPath (Join-Path `$InstallRoot 'Reparo.ps1') -Required
    Write-Host 'Report-only mode complete; Reparo was not installed or run.'
    exit 0
}
"@
    $ninjaCustomFieldUpdate = "    Update-NinjaReparoCustomField -ReparoPath `$installedPath"
}

$script = $template.Replace('__BUNDLED_SHA256__', $sourceHash).Replace('__BUNDLED_GZIP_BASE64__', $base64Literal).Replace('__DEPLOYMENT_LABEL__', $DeploymentLabel).Replace('__NINJA_CUSTOM_FIELD_BLOCK__', $ninjaCustomFieldBlock).Replace('__NINJA_CUSTOM_FIELD_UPDATE__', $ninjaCustomFieldUpdate)
$outputDirectory = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}
[System.IO.File]::WriteAllText($OutputPath, $script, [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated: $OutputPath"
Write-Host "Embedded Reparo SHA-256: $sourceHash"
